import { Panel } from '@/types/panel'

export const panels: Panel[] = [
{
        name: 'Painel 1',
        health: 87,
        operatingPeriod: '09h00 - 18h00',
        currentEnergy: 23,
        storedEnergy: 34,
        brand: 'Marca 1',
        model: 'XXY-23',
        status: "Funcionando",
    },
    {
        name: 'Painel 2',
        health: 90,
        operatingPeriod: '08h00 - 17h00',
        currentEnergy: 28,
        storedEnergy: 40,
        brand: 'Marca 2',
        model: 'ABC-45',
        status: "Funcionando",
    },
    {
        name: 'Painel 3',
        health: 75,
        operatingPeriod: '10h00 - 19h00',
        currentEnergy: 20,
        storedEnergy: 30,
        brand: 'Marca 3',
        model: 'DEF-67',
        status: "Problema",
    },
    {
        name: 'Painel 4',
        health: 80,
        operatingPeriod: '07h00 - 16h00',
        currentEnergy: 25,
        storedEnergy: 35,
        brand: 'Marca 4',
        model: 'GHI-89',
        status: "Funcionando",
    },
    {
        name: 'Painel 5',
        health: 85,
        operatingPeriod: '11h00 - 20h00',
        currentEnergy: 22,
        storedEnergy: 32,
        brand: 'Marca 5',
        model: 'JKL-01',
        status: "Desligado",
    },
    {
        name: 'Painel 6',
        health: 78,
        operatingPeriod: '06h00 - 15h00',
        currentEnergy: 18,
        storedEnergy: 25,
        brand: 'Marca 6',
        model: 'MNO-23',
        status: "Alerta",
    },
    {
        name: 'Painel 7',
        health: 92,
        operatingPeriod: '09h00 - 18h00',
        currentEnergy: 30,
        storedEnergy: 45,
        brand: 'Marca 7',
        model: 'PQR-45',
        status: "Funcionando",
    },
    {
        name: 'Painel 8',
        health: 81,
        operatingPeriod: '10h00 - 19h00',
        currentEnergy: 24,
        storedEnergy: 38,
        brand: 'Marca 8',
        model: 'STU-67',
        status: "Funcionando",
    }
]